//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleProblem", Namespace="http://schemas.datacontract.org/2004/07/HelpDriverBuddy.Service.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem[]))]
    public partial class VehicleProblem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object VehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object VehicleOwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateOn {
            get {
                return this.CreateOnField;
            }
            set {
                if ((this.CreateOnField.Equals(value) != true)) {
                    this.CreateOnField = value;
                    this.RaisePropertyChanged("CreateOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Vehicle {
            get {
                return this.VehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleField, value) != true)) {
                    this.VehicleField = value;
                    this.RaisePropertyChanged("Vehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object VehicleOwner {
            get {
                return this.VehicleOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleOwnerField, value) != true)) {
                    this.VehicleOwnerField = value;
                    this.RaisePropertyChanged("VehicleOwner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelpDriverBuddyService.IHelpDriverBuddyService")]
    public interface IHelpDriverBuddyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpDriverBuddyService/GetVehicleProblems", ReplyAction="http://tempuri.org/IHelpDriverBuddyService/GetVehicleProblemsResponse")]
        HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem[] GetVehicleProblems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpDriverBuddyService/GetVehicleProblems", ReplyAction="http://tempuri.org/IHelpDriverBuddyService/GetVehicleProblemsResponse")]
        System.Threading.Tasks.Task<HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem[]> GetVehicleProblemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpDriverBuddyService/AddVecleProblem", ReplyAction="http://tempuri.org/IHelpDriverBuddyService/AddVecleProblemResponse")]
        void AddVecleProblem(HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem infomation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpDriverBuddyService/AddVecleProblem", ReplyAction="http://tempuri.org/IHelpDriverBuddyService/AddVecleProblemResponse")]
        System.Threading.Tasks.Task AddVecleProblemAsync(HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem infomation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelpDriverBuddyServiceChannel : HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.IHelpDriverBuddyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelpDriverBuddyServiceClient : System.ServiceModel.ClientBase<HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.IHelpDriverBuddyService>, HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.IHelpDriverBuddyService {
        
        public HelpDriverBuddyServiceClient() {
        }
        
        public HelpDriverBuddyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelpDriverBuddyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelpDriverBuddyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelpDriverBuddyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem[] GetVehicleProblems() {
            return base.Channel.GetVehicleProblems();
        }
        
        public System.Threading.Tasks.Task<HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem[]> GetVehicleProblemsAsync() {
            return base.Channel.GetVehicleProblemsAsync();
        }
        
        public void AddVecleProblem(HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem infomation) {
            base.Channel.AddVecleProblem(infomation);
        }
        
        public System.Threading.Tasks.Task AddVecleProblemAsync(HelpDriverBuddy.Service.ClientLibrary.HelpDriverBuddyService.VehicleProblem infomation) {
            return base.Channel.AddVecleProblemAsync(infomation);
        }
    }
}
